import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" py-4 px-6 container max-w-[1024px] mx-auto">
          <Header />
          {children}
          <footer className="container py-8 text-gray-500">
            jobBoard. &copy; All rights reserved.
          </footer>
        </main>
        </body>
    </html>
  );
}
